### PR TITLE
Add ability to interleave `agent.run` calls with input from the user

### PR DESCRIPTION
**Pull request by evangriffiths**
Two new features:

- New method `Agent.execute_command`. i.e. bootstrapping the agent, but not necessarily just at the start
- New argument, `resume` on `Agent.run` method. Doesn't wipe agent history and start again.

Example usage of the new features

```
agent = Agent(llm=LLM(generator=generator), engine=engine)
agent.prompt = f"Reason step by step. {engine.help}"

# Run a number of steps autonomously
agent.run(iterations=2)
# Get input from the user
agent.execute_command(...)
# Continue running autonomously
agent.run(iterations=3, resume=True)
```

### CODE REVIEW

**Comment by evangriffiths** [comment]
A full example:

```
from microchain import LLM, Agent, Engine, Function, OpenAIChatGenerator

class FortunatelyEvent(Function):
    @property
    def description(self) -> str:
        return "Continue the story with a new fortunate development. Start with 'Fortunately, ...'"

    @property
    def example_args(self) -> list[str]:
        return ["Fortunately, his grandmother had baked a cake."]

    def __call__(self, event: str) -> str:
        return event

class UnfortunatelyEvent(Function):
    @property
    def description(self) -> str:
        return "Continue the story with a new unfortunate development. Start with 'Unfortunately, ...'"

    @property
    def example_args(self) -> list[str]:
        return ["Unfortunately, the family dog had eaten it before he arrived."]

    def __call__(self, event: str) -> str:
        return event

engine = Engine()
engine.register(FortunatelyEvent())
engine.register(UnfortunatelyEvent())
generator = OpenAIChatGenerator(
    model="gpt-4-turbo-preview",
    api_key=...,
    api_base="https://api.openai.com/v1",
    temperature=0.7,
)
agent = Agent(llm=LLM(generator=generator), engine=engine)
agent.prompt = (
    f"Tell a story, alternating between fortunate and unfortunate events. "
    f"{engine.help}"
    f"It starts with: 'Milo was walking from school to visit his grandmother, "
    f"when ...'"
)
agent.bootstrap = [
    f'UnfortunatelyEvent("Unfortunately, his grandmother was not home.")'
]
# Run a number of steps autonomously
agent.run(iterations=2)

# Get input from the user
agent.execute_command(
    'FortunatelyEvent("Milo could always find ways out of a tricky situations")'
)

# Continue running autonomously
agent.run(iterations=3, resume=True)
```

Gives output:
```
...
Continue the story with a new unfortunate development. Start with 'Unfortunately, ...'.
Example: UnfortunatelyEvent(event=Unfortunately, the family dog had eaten it before he arrived.)
It starts with: 'Milo was walking from school to visit his grandmother, when ...'
Running 2 iterations
>> UnfortunatelyEvent("Unfortunately, his grandmother was not home.")
Unfortunately, his grandmother was not home.
>> FortunatelyEvent("Fortunately, he found a key under the mat and let himself in.")
Fortunately, he found a key under the mat and let himself in.
>> UnfortunatelyEvent("Unfortunately, as soon as he entered, he realized the power was out.")
Unfortunately, as soon as he entered, he realized the power was out.
Finished 2 iterations
>> FortunatelyEvent("Milo could always find ways out of a tricky situations")
Milo could always find ways out of a tricky situations
>> UnfortunatelyEvent("Unfortunately, this time he stumbled in the dark and knocked over a vase.")
Unfortunately, this time he stumbled in the dark and knocked over a vase.
>> FortunatelyEvent("Fortunately, the vase was not one of his grandmother's precious antiques, but rather a cheap replica.")
Fortunately, the vase was not one of his grandmother's precious antiques, but rather a cheap replica.
>> UnfortunatelyEvent("Unfortunately, the noise alerted a neighbor who, thinking there was a burglar, called the police.")
Unfortunately, the noise alerted a neighbor who, thinking there was a burglar, called the police.
Finished 3 iterations
```

**Comment by galatolofederico** [comment]
Nice! looks good to me! thank you for the PR!

**Comment by evangriffiths** [comment]
@galatolofederico Thanks for the merge. Would you mind making a new release?

**Comment by galatolofederico** [comment]
Sure!

**Pull request merged**
