### PR TITLE
Allow setting of user- and system-prompt

### PR DESCRIPTION
**Pull request by evangriffiths**
Is there any reason why the user shouldn't be able to set both? I think it's quite a normal thing to do

### CODE REVIEW

**Comment by galatolofederico** [comment]
The reason for this is that some models have a dedicated system prompt, while others do not. I added the prompt as a regular message to accommodate models without a system prompt. Initially, I thought that having both a true system prompt and a "first message as system prompt" might confuse the user, so I decided against allowing both. However, I might have been overly cautious. We can remove this restriction and allow both prompts to be set. Perhaps we could add a warning if both are configured?

**Comment by evangriffiths** [comment]
Ah I see. But currently the only supported generators are OpenAI and llama3.1 via replicate, and they both allow user+system prompts.

The two options that make sense to me would be:
1. Move the check and exception to inside the Generator that doesn't support user and system prompts, or
2. Don't worry about checking in microchain, and leave whatever client is being used to throw the exception.

But if you'd like to keep it in it's not a big problem - for this case it's easy to work around. Instead of:
```
agent.prompt = "What is 22 + 9?"`
agent.run(iterations=1)
```
you can just do:
```
user_prompt = {
    "role": "user",
    "content": "What is 22 + 9?",
}
agent.run(iterations=1, transient_history=[user_prompt])
```

**Comment by evangriffiths** [comment]
> I thought that having both a true system prompt and a "first message as system prompt" might confuse the user, so I decided against allowing both

I think this is quite normal to have both, where the system prompt describes general behaviour, and the user prompt describes some specific task:

```
prompt = """
SYSTEM: you are a helpful assistant.

USER: Help me this this specific task...
"""
```
so hopefully the user won't be confused by this 😄

**Comment by galatolofederico** [comment]
Yeah, you're right. I overthought this too much. :joy:  Let's remove the check and let the users decide for themselves.

**Pull request merged**
