### PR TITLE
Add Llama 3.1 Generator

### PR DESCRIPTION
**Pull request by kongzii**
Hi, the new LLama 3.1 is pretty good and, from the first experiments, actually usable in projects like this! Adding the support in this PR.

### CODE REVIEW

**Comment by galatolofederico** [comment]
Hey, thank you so much for the PR!

Before the merge, I have a quick suggestion: using `hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4` as the default model might be a bit too opinionated. It might be better to use a more neutral default, such as `meta/meta-llama-3.1-405b-instruct`, or perhaps not set a default model at all.

Thanks again for your contribution!

**Comment by kongzii** [comment]
Thanks for the fast response!

`tokenizer_pretrained_model_name_or_path: str = "hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4"` is used only for the tokenizer, I used this one instead of the official meta one because for the meta one, you need to accept their terms and be logged in via the CLI.

Agreed that there doesn't have to be any default at all, because `model: str,` also doesn't have any default value, going to change it.

**Comment by galatolofederico** [comment]
Nice! LGTM, i will merge and bump the version!

**Comment by galatolofederico** [comment]
Nice! LGTM. I will merge it and tag the new version for the PyPI CI/CD

**Pull request merged**
